CreateRol:
    path: /Role/create/
    controller: App\Infrastructure\Controller\RoleController::createRole
    methods: [GET]

UpdateRol:
    path: /Role/update/
    controller: App\Infrastructure\Controller\RoleController::updateRole
    methods: [GET]

AllRoles:
    path: /Role/
    controller: App\Infrastructure\Controller\RoleController::all

CreateDepartment:
    path: /Department/create/
    controller: App\Infrastructure\Controller\DepartmentController::createDepartment
    methods: [GET]

UpdateDepartment:
    path: /Department/update/
    controller: App\Infrastructure\Controller\DepartmentController::updateDepartment
    methods: [GET]

CreateParentDepartment:
    path: /ParentDepartment/create/
    controller: App\Infrastructure\Controller\ParentDepartmentController::createParentDepartment
    methods: [GET]

UpdateParentDepartment:
    path: /ParentDepartment/update/
    controller: App\Infrastructure\Controller\ParentDepartmentController::updateParentDepartment
    methods: [GET]

CheckNickName:
    path: /Manager/checkNickName/
    controller: App\Infrastructure\Controller\ManagerController::checkNickName
    methods: [GET]

CheckEmail:
    path: /Manager/checkEmail/
    controller: App\Infrastructure\Controller\ManagerController::checkEmail
    methods: [GET]

CreateManager:
    path: /Manager/create/
    controller: App\Infrastructure\Controller\ManagerController::createManager
    methods: [GET]

UpdateManager:
    path: /Manager/update/
    controller: App\Infrastructure\Controller\ManagerController::updateManager
    methods: [GET]

CreateClotheCategory:
    path: /ClotheCategory/create/
    controller: App\Infrastructure\Controller\ClotheCategoryController::createClotheCategory
    methods: [GET]

UpdateClotheCategory:
    path: /ClotheCategory/update/
    controller: App\Infrastructure\Controller\ClotheCategoryController::updateClotheCategory
    methods: [GET]

CreateContract:
    path: /Contract/create/
    controller: App\Infrastructure\Controller\ContractController::createContract
    methods: [GET]
