app_file_role:
    resource: 'routes/context/role.yaml'

app_file_department:
    resource: 'routes/context/departament.yaml'

app_file_manager:
    resource: 'routes/context/manager.yaml'

app_file_clothe:
    resource: 'routes/context/clothe.yaml'

app_file_parentDepartment:
    resource: 'routes/context/parentDepartment.yaml'

app_file_clotheCategory:
    resource: 'routes/context/clotheCategory.yaml'

app_file_contract:
    resource: 'routes/context/contract.yaml'

app_file_user:
    resource: 'routes/context/user.yaml'

app_file_gender:
    resource: 'routes/context/gender.yaml'

app_file_sizeType:
    resource: 'routes/context/sizeType.yaml'

app_file_size:
    resource: 'routes/context/size.yaml'

app_file_clotheSizeStock:
    resource: 'routes/context/clotheSizeStock.yaml'

app_file_order:
   resource: 'routes/context/order.yaml'

app_file_orderDetails:
  resource: 'routes/context/ordeDetails.yaml'

app_file_delivery:
   resource: 'routes/context/delivery.yaml'

