CreateRol:
    path: /Role/create/
    controller: App\Infrastructure\Controller\RoleController::createRole
    methods: [GET]

UpdateRol:
    path: /Role/update/
    controller: App\Infrastructure\Controller\RoleController::updateRole
    methods: [GET]

AllRoles:
    path: /Role/
    controller: App\Infrastructure\Controller\RoleController::all
    methods: [GET]

