# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Infrastructure\Controller\:
        resource: '../src/Infrastructure/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.role_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\Role\Role

    App\Domain\Model\Role\RoleRepository:
        alias: app.role_repository

    app.department_repository:
            class: Doctrine\ORM\EntityRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - App\Domain\Model\Department\Department

    App\Domain\Model\Department\DepartmentRepository:
        alias: app.department_repository

    app.parentDepartament_repository:
            class: Doctrine\ORM\EntityRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - App\Domain\Model\ParentDepartment\ParentDepartment

    App\Domain\Model\ParentDepartment\ParentDepartmentRepository:
            alias: app.parentDepartament_repository

    app.manager_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\Manager\Manager

    App\Domain\Model\Manager\ManagerRepository:
        alias: app.manager_repository

    app.clothecategory_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\ClotheCategory\ClotheCategory

    App\Domain\Model\ClotheCategory\ClotheCategoryRepository:
        alias: app.clothecategory_repository

    app.contract_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\Contract\Contract

    App\Domain\Model\Contract\ContractRepository:
        alias: app.contract_repository

    app.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\User\User

    App\Domain\Model\User\UserRepository:
        alias: app.user_repository

    app.delete_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\DeleteThing\DeleteThing

    App\Domain\Model\DeleteThing\DeleteThingRepository:
        alias: app.delete_repository

    app.clothe_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\Clothe\Clothe

    App\Domain\Model\Clothe\ClotheRepository:
        alias: app.clothe_repository

    app.clotheSizeStock_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\ClotheSizeStock\ClotheSizeStock

    App\Domain\Model\ClotheSizeStock\ClotheSizeStockRepository:
        alias: app.clotheSizeStock_repository

    App\EventListener\ExceptionListener:
                tags:
                    - { name: kernel.event_listener, event: kernel.exception }

    Manager.all_handler:
                class: App\Application\Manager\GetAll\ManagerGetAll
                tags:
                    - { name: tactician.handler, command: App\Application\Manager\GetAll\ManagerGetAllCommand }

    Manager.checkNickName_handler:
                class: App\Application\Manager\CheckNickName\ManagerCheckNickName
                tags:
                    - { name: tactician.handler, command: App\Application\Manager\CheckNickName\ManagerCheckNickNameCommand }

    Manager.checkEmail_handler:
                class: App\Application\Manager\CheckEmail\ManagerCheckEmail
                tags:
                    - { name: tactician.handler, command: App\Application\Manager\CheckEmail\ManagerCheckEmailCommand }

    Manager.update_handler:
                class: App\Application\Manager\Update\ManagerUpdate
                tags:
                    - { name: tactician.handler, command: App\Application\Manager\Update\ManagerUpdateCommand }

    Manager.create_handler:
                class: App\Application\Manager\Create\ManagerCreate
                tags:
                    - { name: tactician.handler, command: App\Application\Manager\Create\ManagerCreateCommand }

    Manager.delete_handler:
                class: App\Application\Manager\Delete\ManagerDelete
                tags:
                    - { name: tactician.handler, command: App\Application\Manager\Delete\ManagerDeleteCommand }