CreateClotheCategory:
    path: /ClotheCategory/create/
    controller: App\Infrastructure\Controller\ClotheCategoryController::createClotheCategory
    methods: [POST]

UpdateClotheCategory:
    path: /ClotheCategory/update/
    controller: App\Infrastructure\Controller\ClotheCategoryController::updateClotheCategory
    methods: [POST]

DeleteClotheCategory:
    path: /ClotheCategory/delete/
    controller: App\Infrastructure\Controller\ClotheCategoryController::deleteClotheCategory
    methods: [GET]

GetClotheCategory:
    path: /ClotheCategory/
    controller: App\Infrastructure\Controller\ClotheCategoryController::all
    methods: [GET]