CreateDelivery:
    path: /Delivery/create/
    controller: App\Infrastructure\Controller\DeliveryController::createDelivery
    methods: [POST]

GetDelivery:
    path: /Delivery/
    controller: App\Infrastructure\Controller\DeliveryController::getByOrderId
    methods: [GET]