CreateOrder:
    path: /Order/create/
    controller: App\Infrastructure\Controller\OrderController::createOrder
    methods: [POST]

DeleteOrder:
    path: /Order/delete/
    controller: App\Infrastructure\Controller\OrderController::deleteOrder
    methods: [POST]