CreateParentDepartment:
    path: /ParentDepartment/create/
    controller: App\Infrastructure\Controller\ParentDepartmentController::createParentDepartment
    methods: [POST]

UpdateParentDepartment:
    path: /ParentDepartment/update/
    controller: App\Infrastructure\Controller\ParentDepartmentController::updateParentDepartment
    methods: [POST]

DeleteParentDepartment:
    path: /ParentDepartment/delete/
    controller: App\Infrastructure\Controller\ParentDepartmentController::deleteParentDepartment
    methods: [POST]


GetAllParentDepartment:
    path: /ParentDepartment/
    controller: App\Infrastructure\Controller\ParentDepartmentController::getAllParentDepartment
    methods: [GET]