CreateUser:
    path: /User/create/
    controller: App\Infrastructure\Controller\UserController::createUser
    methods: [POST]

UpdateUser:
    path: /User/update/
    controller: App\Infrastructure\Controller\UserController::updateUser
    methods: [POST]

DeleteUser:
    path: /User/delete/
    controller: App\Infrastructure\Controller\UserController::deleteUser
    methods: [POST]