CreateUser:
    path: /User/create/
    controller: App\Infrastructure\Controller\UserController::createUser
    methods: [POST]

UpdateUser:
    path: /User/update/
    controller: App\Infrastructure\Controller\UserController::updateUser
    methods: [POST]

DeleteUser:
    path: /User/delete/
    controller: App\Infrastructure\Controller\UserController::deleteUser
    methods: [POST]

OneUser:
    path: /User/one/
    controller: App\Infrastructure\Controller\UserController::oneUser
    methods: [GET]

FilterUser:
    path: /User/filter/
    controller: App\Infrastructure\Controller\UserController::filterUser
    methods: [GET]