services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    App\:
        resource: '../../src/*'
        exclude: '../../src/{Entity,Migrations,Tests,Kernel.php}'

    app.role_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\Role\Role

    App\Domain\Model\Role\RoleRepository:
        alias: app.role_repository

    app.department_repository:
            class: Doctrine\ORM\EntityRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - App\Domain\Model\Department\Department

    App\Domain\Model\Department\DepartmentRepository:
        alias: app.department_repository

    app.parentDepartament_repository:
            class: Doctrine\ORM\EntityRepository
            factory: ['@doctrine.orm.default_entity_manager', getRepository]
            arguments:
                - App\Domain\Model\ParentDepartment\ParentDepartment

    App\Domain\Model\ParentDepartment\ParentDepartmentRepository:
            alias: app.parentDepartament_repository

    app.manager_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\Manager\Manager

    App\Domain\Model\Manager\ManagerRepository:
        alias: app.manager_repository

    app.clothecategory_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\ClotheCategory\ClotheCategory

    App\Domain\Model\ClotheCategory\ClotheCategoryRepository:
        alias: app.clothecategory_repository

    app.contract_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\Contract\Contract

    App\Domain\Model\Contract\ContractRepository:
        alias: app.contract_repository

    app.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\User\User

    App\Domain\Model\User\UserRepository:
        alias: app.user_repository

    app.delete_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\DeleteThing\DeleteThing

    App\Domain\Model\DeleteThing\DeleteThingRepository:
        alias: app.delete_repository

    app.clothe_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\Clothe\


    App\Domain\Model\Clothe\ClotheRepository:
        alias: app.clothe_repository

    app.clotheSizeStock_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Domain\Model\ClotheSizeStock\ClotheSizeStock

    App\Domain\Model\ClotheSizeStock\ClotheSizeStockRepository:
        alias: app.clotheSizeStock_repository
