services:

    _defaults:
        autowire: true

    clotheCategory.create_handler:
                class: App\Application\ClotheCategory\Create\ClotheCategoryCreate
                tags:
                    - { name: tactician.handler, command: App\Application\ClotheCategory\Create\ClotheCategoryCreateCommand }

    clotheCategory.update_handler:
                class: App\Application\ClotheCategory\Update\ClotheCategoryUpdate
                tags:
                    - { name: tactician.handler, command: App\Application\ClotheCategory\Update\ClotheCategoryUpdateCommand }

    clotheCategory.delete_handler:
                    class: App\Application\ClotheCategory\Delete\ClotheCategoryDelete
                    tags:
                        - { name: tactician.handler, command: App\Application\ClotheCategory\Delete\ClotheCategoryDeleteCommand }

    clotheCategory.get_handler:
                        class: App\Application\ClotheCategory\GetAll\ClotheCategoryAll
                        tags:
                            - { name: tactician.handler, command: App\Application\ClotheCategory\GetAll\ClotheCategoryAllCommand }