services:

    _defaults:
        autowire: true

    Department.create_handler:
                class: App\Application\Gender\AllGenders\GenderAll
                tags:
                    - { name: tactician.handler, command: App\Application\Gender\AllGenders\GenderAllCommand }