services:

    _defaults:
        autowire: true

    order.create_handler:
                class: App\Application\Order\Create\OrderCreate
                tags:
                    - { name: tactician.handler, command: App\Application\Order\Create\OrderCreateCommand }

    order.delete_handler:
                    class: App\Application\Order\Delete\OrderClotheDelete
                    tags:
                        - { name: tactician.handler, command: App\Application\Order\Delete\OrderClotheDeleteCommand }

    order.getAll_handler:
                        class: App\Application\Order\GetAll\OrderClotheGetAll
                        tags:
                            - { name: tactician.handler, command: App\Application\Order\GetAll\OrderClotheGetAllCommand }

    order.getByUserID_handler:
                            class: App\Application\Order\GetByUserID\OrderClotheGetByUserId
                            tags:
                                - { name: tactician.handler, command: App\Application\Order\GetByUserID\OrderClotheGetByUserIdCommand }