services:

    _defaults:
        autowire: true

    Role.all_handler:
                class: App\Application\Role\AllRoles\RoleAll
                tags:
                    - { name: tactician.handler, command: App\Application\Role\AllRoles\RoleAllCommand }