services:

    _defaults:
        autowire: true

    Department.create_handler:
                class: App\Application\Sizes\SizePart
                tags:
                    - { name: tactician.handler, command: App\Application\Sizes\SizePartCommand }