services:

    _defaults:
        autowire: true

    Department.create_handler:
                class: App\Application\SizeType\AllSizeType\SizeTypeAll
                tags:
                    - { name: tactician.handler, command: App\Application\SizeType\AllSizeType\SizeTypeAllCommand }