services:

    _defaults:
        autowire: true

    User.create_handler:
                class: App\Application\User\Create\UserCreate
                tags:
                    - { name: tactician.handler, command: App\Application\User\Create\UserCreateCommand }

    User.update_handler:
                class: App\Application\User\Update\UserUpdate
                tags:
                    - { name: tactician.handler, command: App\Application\User\Update\UserUpdateCommand }

    User.delete_handler:
                class: App\Application\User\Delete\UserDelete
                tags:
                    - { name: tactician.handler, command: App\Application\User\Delete\UserDeleteCommand }

    User.one_handler:
                class: App\Application\User\GetByUuid\UserGetByUuid
                tags:
                    - { name: tactician.handler, command: App\Application\User\GetByUuid\UserGetByUuidCommand }

    User.filter_handler:
                class: App\Application\User\Filter\UserFilter
                tags:
                    - { name: tactician.handler, command: App\Application\User\Filter\UserFilterCommand }
